### ISSUE TITLE
Bug in defragment page

### ISSUE THREAD

**Issue by eatplayhate** [symisc/vedis#11]
I discovered an issue in the vedis kv store due to the handling of defragmenting slave pages. The defragment function only uses the cell array on the current page, rather than the master page. The fix is to replace the final line in this:

`static int lhPageDefragment(lhpage *pPage)
{
	lhash_kv_engine *pEngine = pPage->pHash;
	unsigned char *zTmp,*zPtr,*zEnd,*zPayload;
	lhcell *pCell;
	/* Get a temporary page from the pager. This opertaion never fail */
	zTmp = pEngine->pIo->xTmpPage(pEngine->pIo->pHandle);
	/* Move the target cells to the begining */
	pCell = pPage->pMaster->pList; /* replaced with pPage->pMaster */`

I have attached an example which will demonstrate corruption of the kv store when performing the sequence of operations in the test file.
[Broken-vedis.zip](https://github.com/symisc/vedis/files/1162041/Broken-vedis.zip)

**Comment by Yuras** [comment]
This looks exactly like https://github.com/symisc/unqlite/issues/5, which is closed, but not fixed.

**Comment by symisc** [comment]
Thank you for your contribution. The bug is now identified in the hash key/value disk store and the patch is merged with the main trunk.
