### ISSUE TITLE
question on vedis cluster

### ISSUE THREAD

**Issue by sandylss** [symisc/vedis#14]
Hi guys,
  I wonder does vedis support cluster deployment?
  In telecommunication, we seek for low latency and high architectural flexibility. I want my service to be stateless, so I choose redis at first but figure out that the several hundred microseconds networking latency between redis client and server is  unsatisfactory. Then I turn to this embedded database.
  So if I'm to build a cluster, do I have to share memory/files and care about details like data consistency between nodes? Is there some official guide on vedis cluster?
  Thanks!

**Comment by symisc** [comment]
Vedis uses a single file on disk to store its data. Do you plan to share this file between multiple nodes across the network?

**Comment by sandylss** [comment]
Thanks for the quick reply.
It's sad I'm new to database. As far as I'm concerned, I may apply some protocols, such as gossip, to ensure data consistency. Or I can share storage files by NFS. Since my goal is just to build a function-work cluster, I may not consider other aspects.

**Comment by symisc** [comment]
In this particular case, you should rely on a distributed database like Cassandra because single disk file db like Vedis or SQLite perform poorly or in same case are unreliable.
