### ISSUE TITLE
Database file format

### ISSUE THREAD

**Issue by walydoura** [symisc/vedis#15]
Hi,
What format is the database file when vedis generates it on disk?
which software should I use to open it properly?

**Comment by hamidb80** [comment]
I guess you have to write a custom plugin for your editor/DB manager to support that. It's not a universal file format, it's designed specially for vedis project.

**Comment by symisc** [comment]
Vedis internally uses the same file format as [UnQLite](https://unqlite.org). Any GUI database manager such as [FastNoSQL](https://fastonosql.com/) should handle/read without issue a vedis disk file.
