### ISSUE TITLE
File descriptor leak

### ISSUE THREAD

**Issue by coleifer** [symisc/vedis#20]
From: https://github.com/coleifer/vedis-python/pull/22

>An error has been made in the SyOSUtilRandomSeed, when running for a long time, leads to a leak of file descriptors, since the /dev/urandom descriptor is not closed anywhere

The patch:

```
diff --git a/src/vedis.c b/src/vedis.c
index 844cfbe..c6336b0 100644
--- a/src/vedis.c
+++ b/src/vedis.c
@@ -12924,6 +12924,7 @@ static sxi32 SyOSUtilRandomSeed(void *pBuf, sxu32 nLen, void *pUnused)
        fd = open("/dev/urandom", O_RDONLY);
        if (fd >= 0 ){
                if( read(fd, zBuf, nLen) > 0 ){
+                 close(fd);
                        return SXRET_OK;
                }
                /* FALL THRU */
```

**Comment by symisc** [comment]
Fixed. Thanks for reporting this @coleifer . Since Vedis shares the same codebase as UnQLite, this file handle leak was fixed back in 2018 in UnQLite, but the fix was never pushed here.
