### ISSUE TITLE
HASH and LIST with On-Disk DB not work on OPENWRT

### ISSUE THREAD

**Issue by taka-wang** [symisc/vedis#4]
Hi,

Thanks for your great package.
I've try to run "vedis_shell" on my OPENWRT (MIPS/Big Endian) Arduino Yun but found some strange behaviours.

Steps as following:
1) vedis_shell /dev/shm/db
2) HSET hello world 1
3) HSET hello today 2
4) exit
5) vedis_shell /dev/shm/db
6) HGET hello world -> "null"

<hr>

1) vedis_shell /dev/shm/db2
2) LPUSH hello world
3) LPUSH hello today
4) exit
5) vedis_shell /dev/shm/db2
6) LINDEX hello 0 -> "null"

<hr>

Binaries are built with uClibc library.
Have you come across this problem？

Thanks

**Comment by hongkongkiwi** [comment]
Seems like a dealbreaker! Any resolution?

**Comment by symisc** [comment]
I don' have any solution to that, but try compiling using the standard c library and another toolchain??!!
